apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argo-application #  give your application name that u wanna deploy into the k8 cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joephilippe/helm-deploy-method.git # the url of github repo u want argocd to track
    targetRevision: HEAD
    path: helm-cmds-use-for-deploy-manifest-files/helm-cmds-use-for-deploy-manifest-files/templates/
  destination:
    server: https://kubernetes.default.svc  
    namespace: helm-deploy  # give ur own name # this is new ns that u want argocd to create

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true  